### ISSUE TITLE
Marko doesn't recognize new components after first build

### ISSUE THREAD

**Issue by Hen2609** [marko-js/vite#37]
### Details

After starting the dev server I created a new component and tried using it. Marko didn't recognize it, needed restart of the server

### Expected Behavior

I expected the component will be recognized and be able to be used without restart

**Comment by jwise7** [comment]
confirming this in the vite-express example code. i get this error when adding a new component:
Internal server error: src/components/app-main/index.marko(4,4): Unable to find entry point for custom tag <test-component2>.
```
  2 |   <h1>Hello! world!</h1>
  3 |   <test-component/>
> 4 |   <test-component2/>
    |    ^^^^^^^^^^^^^^^
  5 |   <app-sections>
  6 |     <@section title="Buttons">
  7 |       <table>
  Plugin: marko-vite:pre
  File: [full path here]/examples/examples/vite-express/src/components/app-main/index.marko
 ....
```

**Comment by jwise7** [comment]
backtracking from that error message via debugger shows that node.extra is undefined here. i'm guessing the issue is still several layers deeper, but might help as a starting point to debug: https://github.com/marko-js/marko/blob/a0970494e0135559812611b40448e2bb12952f63/packages/translator-default/src/tag/custom-tag.js#L27
